CREATE TABLE IF NOT EXISTS `Books` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `userID` INT NOT NULL,
    `bookID` VARCHAR(200) DEFAULT NULL,
    `title` VARCHAR(200) NOT NULL,
    `author` VARCHAR(50) NOT NULL,
    `image` VARCHAR(200) DEFAULT NULL,
    `rating` DECIMAL(3,2) DEFAULT NULL,
    UNIQUE(`userID`, `bookID`)
)